// SPDX-License-Identifier: AGPL-3.0-or-later
// THE INSTRUMENT FOR PUTTING A TABLE'S GEOMETRY WHERE ITS PICTURE SAYS IT IS.
//
// ⚠️ THE DEV, LOOKING AT THE FIRST TABLES WEARING HIS ART: "Todas as imagens estão com os itens fora de
// lugar. O ideal seria você refazer os mapas, ou melhor, fazer um mapa em cima de cada uma das imagens."
//
// He is right, and the reason is not that the geometry was placed badly — it is that it was placed
// FIRST. Six tables were authored against colour bands, the pictures came later, and a bumper that was
// put where the ball goes is not where a picture happens to draw a bumper.
//
// ========================= WHY A SHEET RATHER THAN A GUESS =========================
// ⚠️ THIS REPOSITORY HAS PAID FOR GUESSING AT GEOMETRY FOUR TIMES, and the record is in
// `table/cabinet`: three arcs that broke tables, an outlane mouth widened on a false reading, a probe
// moved three times before somebody measured, and a drone moved four. Every one of them ended the same
// way — measure, then place.
//
// So this writes what a person needs to place something on a picture: the table AS IT WILL SHIP, with
// its geometry drawn over the art, and a ruled grid to read coordinates off. Fifty pixels bright, ten
// pixels faint, so a position can be counted rather than estimated.
//
// ========================= AND WHY A PERSON HAS TO DO IT =========================
// ⚠️ AUTOMATIC PLACEMENT WAS TRIED IN BOTH DIRECTIONS ON 2026-09-06 AND FAILED IN BOTH, for one
// reason: STRUCTURE IS NOT AN OBJECT. The only thing a picture can be measured for is how much it
// varies from pixel to pixel, and plenty of things vary that are not somewhere to put a bumper.
//
//   · Moving components toward detail, unconstrained, proposed putting three of `ion-storm`'s inside
//     the left wall and two through the lane divider. Walls are the highest-contrast thing on any of
//     these pictures.
//   · Constrained to where a ball can be, it then wanted to slide the two halves of one BANK into
//     each other — legal by every rule it had, and no gate here refuses two targets in the same place.
//   · Adding components where detail and ball-traffic coincide pointed, on `low-orbit`, at art 4.1x
//     the median with 11% of the table's peak traffic and nothing on it. It is the word "Orbit". The
//     title. A bumper mounted on the table's own name.
//   · And a gate built on the same measure could not fail: rolling a table's art sixty pixels OUT of
//     alignment scored HIGHER than the aligned art. It was deleted rather than kept green.
//
// So the sheet is an instrument and not an oracle. It says where things are and how far apart they
// are; deciding that a shape is a satellite rather than a caption is a person's job, and every
// automatic proposal that survived was one a person had read first.
//
// ⚠️ AND IT IS A TEST SO THAT IT CANNOT GO STALE. The first playfield sheets were generated by hand
// and were wrong within the hour, because the plunger lane grew a curved top. The Dev's art is
// changing every few minutes as he iterates; a sheet that regenerates with `npm test` describes the
// table that exists.
import { describe, test, expect } from 'vitest';
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { buildPng, magnify, readPng } from './helpers/png.js';
import { drawTable } from '../app/js/gfx/table-view.js';
import { PLAYABLE_TABLES } from '../app/js/table/catalog.js';
import type { AuthoredTable } from '../app/js/table/authored.js';

/** Faint every ten, bright every fifty, brightest every hundred — countable without any lettering. */
function rule(bytes: Uint8ClampedArray, width: number, height: number): void {
  const mark = (x: number, y: number, level: number): void => {
    const at = (y * width + x) * 4;
    // Added rather than set, so the rule shows over dark art and does not hide bright art.
    bytes[at] = Math.min(255, bytes[at]! + level);
    bytes[at + 1] = Math.min(255, bytes[at + 1]! + level);
    bytes[at + 2] = Math.min(255, bytes[at + 2]! + level);
  };
  const level = (n: number): number => (n % 100 === 0 ? 150 : n % 50 === 0 ? 90 : 40);

  for (let x = 0; x < width; x += 10) for (let y = 0; y < height; y++) mark(x, y, level(x));
  for (let y = 0; y < height; y += 10) for (let x = 0; x < width; x++) mark(x, y, level(y));
}

const backdropOf = (table: AuthoredTable): Uint32Array | undefined => {
  const path = `app/assets/tables/${table.name}.png`;
  if (!existsSync(path)) return undefined;
  const art = readPng(readFileSync(path));
  return art.width === table.size.width && art.height === table.size.height ? art.pixels : undefined;
};

describe('the authoring sheets', () => {
  test.each(PLAYABLE_TABLES.map((t) => [t.name, t] as const))(
    '%s: art, geometry and a rule, at shots/authoring/',
    (name, table) => {
      const backdrop = backdropOf(table);
      /**
       * ⚠️ EVERY LAMP LIT, WHICH IS NOT HOW THE TABLE LOOKS AND IS THE POINT. A sheet for placing
       * things has to show everything that can be there — a light wired to a lamp is invisible until
       * that lamp burns, and a component nobody can see is a component nobody will place around.
       */
      const fb = drawTable({
        table,
        litLamps: table.lamps,
        ...(backdrop ? { backdrop } : {}),
        ...(table.storm ? { flareAt: Math.round(table.size.height * 0.35) } : {}),
      });

      rule(fb.bytes, fb.width, fb.height);
      mkdirSync('shots/authoring', { recursive: true });
      writeFileSync(
        `shots/authoring/${name}.png`,
        buildPng(magnify(fb.bytes, fb.width, fb.height, 3), fb.width * 3, fb.height * 3),
      );

      // The sheet is the table's own size, ruled and magnified — not a screen, not a window.
      expect([fb.width, fb.height], `${name} is drawn at its playfield size`)
        .toEqual([table.size.width, table.size.height]);
    },
  );

  test('⚠️ and every playable table has its picture, or the sheets are of nothing', () => {
    // A sheet drawn on colour bands would be a sheet for placing geometry on a table that is about to
    // stop looking like that. `tests/gfx-backdrop` holds the sizes; this holds the count.
    const without = PLAYABLE_TABLES.filter((t) => backdropOf(t) === undefined).map((t) => t.name);

    expect(without, 'these tables have no usable backdrop').toEqual([]);
  });
});
